### ISSUE TITLE
pushing docker images on the undercloud node required setting the registry to localhost

### ISSUE THREAD

**Issue by weshayutin** [redhat-openstack/ansible-role-tripleo-overcloud-prep-containers#2]
See:
https://github.com/redhat-openstack/ansible-role-tripleo-overcloud-prep-containers/blob/master/templates/overcloud-prep-containers.sh.j2#L51

https://github.com/redhat-openstack/ansible-role-tripleo-overcloud-prep-containers/blob/master/templates/overcloud-prep-containers.sh.j2#L123

**Comment by steveb** [comment]
I think this would be fixed by this change https://review.openstack.org/#/c/396460

**Comment by weshayutin** [comment]
yes :) that does fix it!  Thanks Steve
